[2024-02-23T03:34:02.268+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Data-pipeline.check_connection_database scheduled__2024-02-22T00:00:00+00:00 [queued]>
[2024-02-23T03:34:02.282+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Data-pipeline.check_connection_database scheduled__2024-02-22T00:00:00+00:00 [queued]>
[2024-02-23T03:34:02.282+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-23T03:34:02.292+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): check_connection_database> on 2024-02-22 00:00:00+00:00
[2024-02-23T03:34:02.300+0000] {standard_task_runner.py:60} INFO - Started process 294 to run task
[2024-02-23T03:34:02.305+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Data-pipeline', 'check_connection_database', 'scheduled__2024-02-22T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpk08bv3i3']
[2024-02-23T03:34:02.309+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask check_connection_database
[2024-02-23T03:34:02.406+0000] {task_command.py:423} INFO - Running <TaskInstance: Data-pipeline.check_connection_database scheduled__2024-02-22T00:00:00+00:00 [running]> on host 313a02c13f91
[2024-02-23T03:34:03.040+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Data-pipeline' AIRFLOW_CTX_TASK_ID='check_connection_database' AIRFLOW_CTX_EXECUTION_DATE='2024-02-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-22T00:00:00+00:00'
[2024-02-23T03:34:03.232+0000] {logging_mixin.py:188} INFO - Error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pg_database_datname_index"
DETAIL:  Key (datname)=(employee_db) already exists.

[SQL: CREATE DATABASE employee_db]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2024-02-23T03:34:03.232+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-23T03:34:03.241+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Data-pipeline, task_id=check_connection_database, execution_date=20240222T000000, start_date=20240223T033402, end_date=20240223T033403
[2024-02-23T03:34:03.293+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
